name: Tests

on:
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v6
        with:
          node-version: '22'
      - uses: docker/setup-compose-action@v1
      - name: Install dependencies
        shell: bash
        run: bun i
      - name: Build & package
        shell: bash
        run: bun run build
      - name: Install test dependencies
        working-directory: tests
        shell: bash
        run: |-
          cp .env.example .env
          docker compose up -d --wait
          bun i
          bun gen
          bun drizzle-kit migrate
      - name: Test
        working-directory: tests
        shell: bash
        run: |-
          bun test:types
          bun zero-cache-dev > /dev/null 2>&1 &
          sleep 10
          bun run test
      - uses: JoA-MoS/lcov-reporter-action@v1.0.0-alpha.4
        with:
          working-directory: ./tests
